2022-04-21 12:29:23,027 django.request ERROR    Internal Server Error: /items/destribution/delete/1/
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Python\Python310\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Python\Python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Python\Python310\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Python\Python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python\Python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
2022-04-21 12:30:46,354 django.utils.autoreload INFO     D:\Python Projects\Dudhwala\Dudhwala\settings.py changed, reloading.
2022-04-21 12:32:56,984 django.utils.autoreload INFO     Watching for file changes with StatReloader
2022-04-21 12:33:25,371 django.request ERROR    Internal Server Error: /items/destribution/delete/1/
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Python\Python310\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Python\Python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Python\Python310\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Python\Python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python\Python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
2022-04-21 12:35:13,868 django.utils.autoreload INFO     D:\Python Projects\Dudhwala\Items\views.py changed, reloading.
2022-04-21 12:35:15,068 django.utils.autoreload INFO     Watching for file changes with StatReloader
2022-04-21 12:36:25,923 django.utils.autoreload INFO     D:\Python Projects\Dudhwala\Dudhwala\settings.py changed, reloading.
2022-04-21 12:36:26,957 django.utils.autoreload INFO     Watching for file changes with StatReloader
2022-04-21 12:36:46,529 django.utils.autoreload INFO     D:\Python Projects\Dudhwala\Dudhwala\settings.py changed, reloading.
2022-04-21 12:36:47,582 | django.utils.autoreload | INFO     | Watching for file changes with StatReloader
2022-04-21 12:36:53,625 | django.request | ERROR    | Internal Server Error: /items/destribution/delete/1/
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Python\Python310\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Python\Python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Python\Python310\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Python\Python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python\Python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
